query GroupScoresheets ($groupId: ID!) {
  group (groupId: $groupId) {
    id
    name
    scoresheets {
      id
      heat

      competitionEventLookupCode
      participantId
      judgeId
      rulesId
      judgeType

      participantName
      judgeName
      categoryName

      updatedAt
      openedAt
      submittedAt
      completedAt
      didNotSkipAt
    }
  }
}
